### ISSUE TITLE
HTML Indentation (head/body)

### ISSUE THREAD

**Issue by griffinlacek** [Satyakb9/prj-rev-bwfs-dasmoto#1]
Tiny comment, but make sure you indent head and body from your html element as they're children of html. Just something to keep in mind, but a tiny tiny issue :)

https://github.com/Satyakb9/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L3-L8

**Comment by Satyakb9** [comment]
Thanks! I just stuck to Atom's default indentation style, which does not indent head and body elements. Will keep this in mind going forward.
